(*
Program name: Grow_4
Version: 7.4.1 Build: 202
Author: Dr Rafal Urniaz
Subscription: This file is a part of the Grow_4 a scientific software
for structural bioinfiormatics, data visualization and sequence analysis.
It was created and developed by Dr Rafal Urniaz. For more details please
visit http://www.grow4.eu or http://www.biotesseract.com
*)

  com1='Incorrect directory or filename, check it or change the project`s name';
  com2='Main directories was created correctly';
  com3='Directory was NOT created correctly !';
  com4='Problem with read or save a settings';
  com5='New file';
  com6='Insert new filename';
  com7='2<>Problem with read or save a file, check you have a permision to the file or operation';
  com8='Filename exists';
  com9='Error : Divide by zero';
  com10='Invalide range of data';
  com11='Start procedure with "="';
  com12='File not exists';
  com13='Can not create a table';
  com14='Lista nie zawiera projektów lub próbujesz otworzyć plik do ktrego nie masz uprawnień. Upewnij sie czy w panelu bocznym wybrano prawidlową nazwę projektu!';
  com15='Can not sort a data, invalide range of data';
  com16='Not a valid range of data or invalid parameters ! ';
  com17='Enter the column number containing the axis ';
  com18='Invalid file type or type of conversion';
  com19='Potencjalne węgle chiralne : ';
  com20='Imię i nazwisko operatora';
  com21='Podaj imię i nazwisko nowego operatora:';
  com22='Question,...';
  com23='File with the same name exists, repleace it?';
  com24='Raport';
  com25='Total result';
  com26='Information,...';
  com27='Clear all common entries ?';
  com28='U';
  com29='t';
  com30='Syntax error!';
  com31='New';
  com32='Message';
  com33='Czy chcesz stworzyć nową tabelę? ';
  com34='Percent of classified : ';
  com35='Plane are parallel, angle cannot be obtained !';
  com36='2<>Invalid number of records ! Should be included exactly 3 atoms for every group!';
  com37='Please insert the valid PDB ID or code series separated by semicolon (for example 3IL1;3KTD;2XX8)';
  com38='Invalid PDB ID , should has 4 letters or numbers!';
  com39='Export column headers ?';
  com40='0<>File saved in directory : ';
  com41='Analysis will erase current data, start now?';
  com42='Add the partial results into a new table ?';
  com43='Export only common table as an single file? [';
  com44='The help file does not exist. Contact your application vendor for an updated Help file';
  com45='Add a "connect" section?';
  com46='Enter a bookmark number containing the "connect" table, to leave enter "0" :';
  com47='Entries in tables will be recalculated, continue?';
  com48='Entries in tables will be corrected, continue?';
  com49='Columns do not contain the same quantity of records !';
  com50='Do current project as a default? (it will be loaded with the opening of the program)';
  com51='The module combines multiple text files (such as PDB files) into one larger file, do you want to continue?';
  com52='] or NO - export all selected in one PDB file';   // poczatek w 43
  com53='Save changes ?';
  com54='Number of neighbors';
  com55='Improper selection, allowed 3 columns and 3 rows';
  com56='Invalid program direstory, check external programs settings';
  com57='Do you want to save current project?';
  com58='GLUT library did not find! Please supply required file glut32.dll';
  com59='None row seems to be selected in Inc. column in the project table, file can not be generated.';
  com60='1<>"CONECT" table seems to not be included in this project file';
  com61='Podaj numery rekordów oddzielone znakiem separacji " ; " Ranga równa 0, nie jest brana pod uwagę.';
  com62='More than one "CONNECT" section were found, please use the "recalculate CONNECT" and try again, or:'
         +#13#10'(YES) - save adding the first table which was found'
         +#13#10'(NO) - save without any "CONNECT" section'
         +#13#10'(CANCEL) - cancel operation and don`t save the file';
  com63='Are you sure to delete all included models?';
  com64='1<>This column is read only! Please select the correct project name column';
  com65='Suma';
  com66='Średnia arytmetyczna';
  com67='Średnia geometryczna';
  com68='Mediana';
  com69='Moda';
  com70='Odchylenie standardowe';
  com71='Rozstęp';
  com72='Wariancja';
  com73='Wartośc minimalna';
  com74='Wartość maksymalna';
  com75='Wspólczynnik zmienności';
  com76='Wskaźnik skośności';
  com77='Kurtoza';
  com78='Momentem centralnym lV rzędu';
  com79='Number of elements';
  com80='#Erorr';
  com81='Model name has to be unique!, please try again';
  com82='More than one connection table exists in the project,'
        +'please use "combine connect tables" to correct this problem';
  com83='Recalculation is not necessary, only one connect table exists';
  com84=' fixed erorrs! File will be rebuilt and saved.';
  com85='1<help.html>'+'At least one model name is not unique, names will be renamed automatically';
  com86='new';
  com87='Change name,...';
  com88='New name : ' ;
  com89='1<>This table is an index of PDB file any changes can make file unable to'
        +#13#10'open in ecternal programs. Are you sure to include the connect table?';
  com90='0<>Calculation done.';
  com91='0<>Calculation starts on :';
  com92='2<>Processing stop, incorrect file syntax!';
  com93='2<>None model was included in the project table';
  com94='Please insert symbol which will be used to separate CSV file:  ';
  com95='Only one grid can be saved in this format, continue with current grid?';
  com96='Write atom name : ';
  com97='--- Select a molecule ---';
  com98='2<>More than 3 atom selected in one of the group!';
  com99='Please insert a phrase to search in current table : ';
  com100='2<>Not enough atoms selected for the analysis, minimum value is 3 atoms';
  com101='2<>Not enough molecules selected for the analysis, minimum value is 1 molecule';
  com102='Do you want to split current table?';
  com103='1<>Please include only one table to seperation';
  com104='1<>Incorrect input data, at least one value omitted!';
  com105='0<>Rows were replaced : ';
  com106='2<>Not enough rows selected, select exactly 2 rows to replacement';
  com107='Renumber all of the atoms?';
  com108='2<>Not enough atoms selected for the analysis, minimum value is 2 atoms';
  com109='2<>Command line syntax error!';
  com110='1<>Overlay plane not selected!';
  com111='Number of atoms';
  com112='The molecules contain a different number of atoms : ';
  com113='Number of inc. atoms';
  com114='1<>Please include only one record to move';
  com115='2<>Some problems occurred';
  com116='2<>Atoms in residues are not in correct order. Sequences are different or residue names are not presented.';
  com117='Atom coordinates will become the beginning of a new coordinate system, all values will be converted automatically, continue? If "Yes", the default value will be marked as "no alerts before coordinate system changing", no notifications will facilitate the work in GROW_4 environment, but if You need the native coordinate system press "No"';
  com118='Is first record containing a headers?';
  com119='Is first column containing a headers?';
  com120='Please insert a sign of separation:';
  com121='1<>Lists contain different number of cases';
  com122='adequacy :';
  com123='Number of components:';
  com124='CoA :';
  com125='Percent of CoA [PCoA] :';
  com126='Average CoA [aCoA] :';
  com127='CoA 50% :';
  com128='CoA 100% :';
  com129='Q2 QSAR :';
  com130='1<>Syntax error: Atom cannot be rendered:';
  com131='0<>Rendered correctly';
  com132='Undefined value : ' ;
  com133='Error creating graphics';
  com134='Atom list failed during preparation';
  com135='Error: Command cannot be completed, syntax error';
  com136='Please, enter the number of the diagonal to be copied. Range: ';
  com137='1<>Entered value is not a number or is located outside the range.';
  com138='2<>Some problems occurred during the procedure and cannot be completed, please report the error number to the developers team : ';
  com139='Separate signs from values?';
  com140='Please calculate aAPA first';
  com141='File extension *.proj4g was associated with Grow_4 successfully';
  com142='Do you really want to quit the application?'+#10#13+'Modifications not saved will be lost!';
  Com143='Please insert a value : ';
  Com144='The value is incorrect or it is out of allowable range !';
  com145='2<>Selected number of atoms is out of allowable range. Please include exactly 3 (calculated one by one) or 6 (calculated in one molecule) atoms in every molecule.';
  com146='Delete all included records from current table ? ';
  com147='Status: ';
  com148='The 0 items found, operation can not be continued';
  com149='Open browser to download required files ?';
  com150='Current window width is less than 1000 pixels. Gradient function will color the window using this settings, although result may be unreadable. We recommend to not use windows size less than 1000 pixels (width) and 610 pixels (height).';
  com151='During calculations some problem occured, please report this bug.';
  com152='Do you want to apply for all of molecules? If "NO" will be apply for current.';
  com153='Please enter the value according to appropriate type: ';
  com154='Incorrect variable type, expected :';
  com155='Indicate "start" and "end" number for the simulation range';
  com156='Input the values separated by semicolon (;) to indicate the range of macro simulation';
  com157='To add succeeding commands use the "add button". If command requires the number check number checkbox. If command requires the object number, please indiate it in object edit box. If you use additional values remember to add comma (,) separator before the value. For correct syntax evaluate the YASARA bookshelf.';
  com158='Clean the result box ? If "no" new data will be append ?';
  com159='Lists $Res, $Mut, $Val should have an equal number of values, if appear in command script';
  com160='Please indicate the line number separated by semicolon (;) for every line to be extracted. Range is indicated as a number of first (from) and last letter (to) to be extracted.';
  com161='Incorrect data type in the fields !';
  com162='Not enough of selected atoms for the analysis, minimum :';
  com163='The file contains more than 3000 atoms. The application will try to parse the file, although it may stock for a long time. Please do not switch off the application or separate file to smaller parts.';
  com164='Current file will be overwritten, continue?';
  com165='Please select exactly two atoms between which you would like to assign a bond';
  com166='The distance between atoms is more than 3 angstroms. Probability that exists a atomic bond between atoms is very low, are you sure to assign the bond?';
  com167='Please select exactly two atom between which you would like to delete the bond';
  com168='The appropriate program directory was not defined. Please set this values.';
  com169='Unrecognized command: ';

  processing='Operation in progress, please wait ...' ;  //Trawa wykonywanie operacji, prosze czekać,...
  loading='Loading : ';
  pleasewait='Please wait,...';

  // URLs
  PDB_ID_URL='http://www.pdb.org/pdb/files/';
  Help_URL='http://www.grow4.eu';
  GLUT_Url='http://http://user.xmission.com/~nate/glut.html';

  linia= '____________________________________________________________________';
  linia2='--------------------------------------------------------------------';

  roz_sym='.sym';
  roz_ind='.index';
  roz_project='.proj4g';
  roz_grid_template='.gtp';
  file_operator='operator_name.otp' ;
  file_grids_template='grids_template.index';

  // Model types

  type_Protein = 'PRO';
  type_Ligand = 'LIG';
  type_DNA = 'DNA';
  type_RNA = 'RNA';
  type_Plane = 'PLA';
  type_Water = 'HOH';
  type_Analisis = 'ANA';
  type_HeteroAtom = 'HETATM'; // for ligands
  type_Atom = 'ATOM';    // for proteins nucleic acids etc.
  type_Bond='BOND';
  // index filter
  IndexFilter_Any='Any file (*.*)|*.*';


  IndexFilter_1='Grow_4 project file (*.proj4g)|*.proj4g';
  IndexFilter_2='PDB file (*.pdb ; *.ent)|*.pdb;*.ent';
  IndexFilter_3='XML (*.xml)|*.xml';
  IndexFilter_4='CSV (*.csv)|*.csv';
  IndexFilter_5='MOL2 (*.mol2)|*.mol2';
  IndexFilter_6='xMOL (*.xyz)|*.xyz';
  IndexFilter_7='HTML (*.html)|*.html';
  IndexFilter_8='Text file (*.txt)|*.txt';
  IndexFilter_9='Semi-colon separated text file (*.ssv)|*.ssv';
  IndexFilter_10='FASTA text file (*.fasta)|*.fasta';
  IndexFilter_11='Macro text file (*.mcr)|*.mcr';
